### ISSUE TITLE
 Continuous capture  bug（Android5.1.1）

### ISSUE THREAD

**Issue by lx-0713** [google/grafika#117]
07-02 03:44:37.940 4120-4156/com.google.grafika E/AndroidRuntime: FATAL EXCEPTION: Thread-240
    Process: com.google.grafika, PID: 4120
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.android.grafika.CircularEncoder$EncoderThread.drainEncoder(CircularEncoder.java:296)
        at com.android.grafika.CircularEncoder$EncoderThread.frameAvailableSoon(CircularEncoder.java:362)
        at com.android.grafika.CircularEncoder$EncoderThread$EncoderHandler.handleMessage(CircularEncoder.java:470)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at com.android.grafika.CircularEncoder$EncoderThread.run(CircularEncoder.java:251)

**Comment by Michaelj-maker** [comment]
How's the issue with
