### ISSUE TITLE
MoviePlayer doesnt work for an HTTP url

### ISSUE THREAD

**Issue by rahulrj** [google/grafika#45]
The `MoviePlayer` class works fine for a video loaded from sd-card, but it fails with the following error when i try to load a video from a URL. One of the URLs i tried is this
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

I am running the code on Android M.

```
I/MediaHTTPConnection: proxyName: 0.0.0.0 0
13110-14961/com.android.grafika E/NuCachedSource2: source returned error -1, 0 retries left
13110-13110/com.android.grafika E/QComExtractorFactory: Sniff FAIL :: coundn't pull enough data for sniffing
13110-13110/com.android.grafika E/Grafika: Unable to play movie

        java.io.IOException: Failed to instantiate extractor.
        at android.media.MediaExtractor.nativeSetDataSource(Native Method)
        at android.media.MediaExtractor.setDataSource(MediaExtractor.java:182)
        at com.android.grafika.MoviePlayer.<init>(MoviePlayer.java:113)at com.android.grafika.PlayMovieActivity.clickPlayStop(PlayMovieActivity.java:189)
     at java.lang.reflect.Method.invoke(Native Method)
     at android.view.View$DeclaredOnClickListener.onClick(View.java:4450)
     at android.view.View.performClick(View.java:5201)
     at android.view.View$PerformClick.run(View.java:21163)
     at android.os.Handler.handleCallback(Handler.java:746)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5443)
     at java.lang.reflect.Method.invoke(Native Method)
    atcom.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by fadden** [comment]
It looks like MediaExtractor isn't working with your data source.  You should post a question on http://stackoverflow.com/.  Be sure to show the changes you've made.

**Comment by rahulrj** [comment]
@fadden i have tried it with multiple URLs.Are there constraints on URLs or their response headers for it to work?

**Comment by fadden** [comment]
Questions about the Android API should be asked on stackoverflow.com or another suitable forum.  Github issues are for bugs particular to Grafika.

**Comment by rahulrj** [comment]
@fadden If you think its not a Grafika bug, then can you at least give me a HTTP URL for  a video that works correctly with this example?
